# https://taskfile.dev

version: "3"

tasks:
  dev:
    desc: Run all apps in dev mode
    deps:
      - auth
      - app1
      - app2
  auth:
    desc: Run the auth app in dev mode
    dir: auth
    cmds:
      - yarn dev
  app1:
    desc: Run the app1 app in dev mode
    dir: app1
    cmds:
      - yarn dev
  app2:
    desc: Run the app2 app in dev mode
    dir: app2
    cmds:
      - yarn dev
