# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Run all apps in dev mode
    deps:
      - dev
  dev:
    desc: Run all apps in dev mode
    deps:
      - auth
      - app1
      - app2
  up:
    desc: Run docker-compose
    cmds:
      - docker-compose up -d
  down:
    desc: Stop docker-compose
    cmds:
      - docker-compose down
  auth:
    dir: auth
    cmds:
      - yarn dev
  app1:
    dir: app1
    cmds:
      - yarn dev
  app2:
    dir: app2
    cmds:
      - yarn dev
